<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nationalities')->truncate();

        $nationalities = [
            // Priority 1: Kuwaiti
            ['name_en' => 'Kuwaiti', 'name_ar' => 'كويتي', 'category' => 'ARAB', 'sort_order' => 1],

            // Arab Countries (Priority 2)
            ['name_en' => 'Saudi', 'name_ar' => 'سعودي', 'category' => 'ARAB', 'sort_order' => 10],
            ['name_en' => 'Emirati', 'name_ar' => 'إماراتي', 'category' => 'ARAB', 'sort_order' => 11],
            ['name_en' => 'Qatari', 'name_ar' => 'قطري', 'category' => 'ARAB', 'sort_order' => 12],
            ['name_en' => 'Bahraini', 'name_ar' => 'بحريني', 'category' => 'ARAB', 'sort_order' => 13],
            ['name_en' => 'Omani', 'name_ar' => 'عماني', 'category' => 'ARAB', 'sort_order' => 14],
            ['name_en' => 'Egyptian', 'name_ar' => 'مصري', 'category' => 'ARAB', 'sort_order' => 15],
            ['name_en' => 'Moroccan', 'name_ar' => 'مغربي', 'category' => 'ARAB', 'sort_order' => 16],
            ['name_en' => 'Algerian', 'name_ar' => 'جزائري', 'category' => 'ARAB', 'sort_order' => 17],
            ['name_en' => 'Tunisian', 'name_ar' => 'تونسي', 'category' => 'ARAB', 'sort_order' => 18],
            ['name_en' => 'Jordanian', 'name_ar' => 'أردني', 'category' => 'ARAB', 'sort_order' => 19],
            ['name_en' => 'Lebanese', 'name_ar' => 'لبناني', 'category' => 'ARAB', 'sort_order' => 20],
            ['name_en' => 'Syrian', 'name_ar' => 'سوري', 'category' => 'ARAB', 'sort_order' => 21],
            ['name_en' => 'Iraqi', 'name_ar' => 'عراقي', 'category' => 'ARAB', 'sort_order' => 22],
            ['name_en' => 'Palestinian', 'name_ar' => 'فلسطيني', 'category' => 'ARAB', 'sort_order' => 23],
            ['name_en' => 'Libyan', 'name_ar' => 'ليبي', 'category' => 'ARAB', 'sort_order' => 24],
            ['name_en' => 'Sudanese', 'name_ar' => 'سوداني', 'category' => 'ARAB', 'sort_order' => 25],
            ['name_en' => 'Yemeni', 'name_ar' => 'يمني', 'category' => 'ARAB', 'sort_order' => 26],
            ['name_en' => 'Mauritanian', 'name_ar' => 'موريتاني', 'category' => 'ARAB', 'sort_order' => 27],
            ['name_en' => 'Somali', 'name_ar' => 'صومالي', 'category' => 'ARAB', 'sort_order' => 28],
            ['name_en' => 'Djiboutian', 'name_ar' => 'جيبوتي', 'category' => 'ARAB', 'sort_order' => 29],
            ['name_en' => 'Comorian', 'name_ar' => 'قمري', 'category' => 'ARAB', 'sort_order' => 30],

            // Foreign (A-Z)
            ['name_en' => 'Afghan', 'name_ar' => 'أفغاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Albanian', 'name_ar' => 'ألباني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'American', 'name_ar' => 'أمريكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Andorran', 'name_ar' => 'أندوري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Angolan', 'name_ar' => 'أنغولي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Argentine', 'name_ar' => 'أرجنتيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Armenian', 'name_ar' => 'أرمني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Australian', 'name_ar' => 'أسترالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Austrian', 'name_ar' => 'نمساوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Azerbaijani', 'name_ar' => 'أذربيجاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Belgian', 'name_ar' => 'بلجيكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bosnian', 'name_ar' => 'بوسني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Brazilian', 'name_ar' => 'برازيلي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'British', 'name_ar' => 'بريطاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bulgarian', 'name_ar' => 'بلغاري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Cameroonian', 'name_ar' => 'كاميروني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Canadian', 'name_ar' => 'كندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Chilean', 'name_ar' => 'تشيلي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Chinese', 'name_ar' => 'صيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Colombian', 'name_ar' => 'كولومبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Croatian', 'name_ar' => 'كرواتي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Czech', 'name_ar' => 'تشيكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Danish', 'name_ar' => 'دنماركي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Dutch', 'name_ar' => 'هولندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Finnish', 'name_ar' => 'فنلندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'French', 'name_ar' => 'فرنسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Georgian', 'name_ar' => 'جورجي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'German', 'name_ar' => 'ألماني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ghanaian', 'name_ar' => 'غاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Greek', 'name_ar' => 'يوناني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Guinean', 'name_ar' => 'غيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Haitian', 'name_ar' => 'هايتي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Hungarian', 'name_ar' => 'هنغاري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Icelandic', 'name_ar' => 'آيسلندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Indian', 'name_ar' => 'هندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Indonesian', 'name_ar' => 'إندونيسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Iranian', 'name_ar' => 'إيراني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Irish', 'name_ar' => 'أيرلندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Italian', 'name_ar' => 'إيطالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ivorian', 'name_ar' => 'إيفواري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Jamaican', 'name_ar' => 'جامايكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Japanese', 'name_ar' => 'ياباني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Kazakh', 'name_ar' => 'كازاخستاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Kenyan', 'name_ar' => 'كيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Kyrgyz', 'name_ar' => 'قيرغيزستاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Mali', 'name_ar' => 'مالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Mexican', 'name_ar' => 'مكسيكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Moldovan', 'name_ar' => 'مولدوفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Montenegrin', 'name_ar' => 'مونتينيغري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'New Zealander', 'name_ar' => 'نيوزيلندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Nigerian', 'name_ar' => 'نيجيري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'North Macedonian', 'name_ar' => 'مقدوني شمالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Norwegian', 'name_ar' => 'نرويجي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Pakistani', 'name_ar' => 'باكستاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Panamanian', 'name_ar' => 'بنمي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Paraguayan', 'name_ar' => 'باراغواياني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Peruvian', 'name_ar' => 'بيروفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Polish', 'name_ar' => 'بولندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Portuguese', 'name_ar' => 'برتغالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Romanian', 'name_ar' => 'روماني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Russian', 'name_ar' => 'روسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Senegalese', 'name_ar' => 'سنغالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Serbian', 'name_ar' => 'صربي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Slovak', 'name_ar' => 'سلوفاكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Slovenian', 'name_ar' => 'سلوفيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'South African', 'name_ar' => 'جنوب أفريقي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'South Korean', 'name_ar' => 'كوري جنوبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Spanish', 'name_ar' => 'إسباني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Swedish', 'name_ar' => 'سويدي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Swiss', 'name_ar' => 'سويسري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Thai', 'name_ar' => 'تايلاندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Turkish', 'name_ar' => 'تركي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ukrainian', 'name_ar' => 'أوكراني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Uruguayan', 'name_ar' => 'أوروغواياني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Uzbek', 'name_ar' => 'أوزبكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Venezuelan', 'name_ar' => 'فنزويلي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Vietnamese', 'name_ar' => 'فيتنامي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Welsh', 'name_ar' => 'ويلزي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Zambian', 'name_ar' => 'زامبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Zimbabwean', 'name_ar' => 'زيمبابوي', 'category' => 'FOREIGN', 'sort_order' => 100],

            // Additional countries
            ['name_en' => 'Antiguan', 'name_ar' => 'أنتيغوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bahamian', 'name_ar' => 'بهامي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bangladeshi', 'name_ar' => 'بنغلاديشي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Barbadian', 'name_ar' => 'باربادوسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Belarusian', 'name_ar' => 'بيلاروسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Belizean', 'name_ar' => 'بليزي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Beninese', 'name_ar' => 'بنيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bhutanese', 'name_ar' => 'بوتاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bolivian', 'name_ar' => 'بوليفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Botswanan', 'name_ar' => 'بوتسواني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bruneian', 'name_ar' => 'برونايي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Burkinabe', 'name_ar' => 'بوركيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Burundian', 'name_ar' => 'بوروندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Cabo Verdean', 'name_ar' => 'رأس الأخضري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Cambodian', 'name_ar' => 'كمبودي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Central African', 'name_ar' => 'وسط أفريقي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Chadian', 'name_ar' => 'تشادي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Congolese', 'name_ar' => 'كونغولي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Costa Rican', 'name_ar' => 'كوستاريكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Cuban', 'name_ar' => 'كوبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Cypriot', 'name_ar' => 'قبرصي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Dominican', 'name_ar' => 'دومينيكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ecuadorian', 'name_ar' => 'إكوادوري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Salvadoran', 'name_ar' => 'سلفادوري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Equatorial Guinean', 'name_ar' => 'غيني استوائي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Eritrean', 'name_ar' => 'إريتري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Estonian', 'name_ar' => 'إستوني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Swati', 'name_ar' => 'إسواتيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ethiopian', 'name_ar' => 'إثيوبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Fijian', 'name_ar' => 'فيجي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Gabonese', 'name_ar' => 'غابوني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Gambian', 'name_ar' => 'غامبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Grenadian', 'name_ar' => 'غرينادي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Guatemalan', 'name_ar' => 'غواتيمالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Bissau-Guinean', 'name_ar' => 'غينيا بيساوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Guyanese', 'name_ar' => 'غوياني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Honduran', 'name_ar' => 'هندوراسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Kiribatian', 'name_ar' => 'كيريباتي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Kosovar', 'name_ar' => 'كوسوفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Lao', 'name_ar' => 'لاوسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Latvian', 'name_ar' => 'لاتفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Lesothan', 'name_ar' => 'ليسوتي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Liberian', 'name_ar' => 'ليبيري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Liechtensteiner', 'name_ar' => 'ليختنشتايني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Lithuanian', 'name_ar' => 'ليتواني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Luxembourgish', 'name_ar' => 'لوكسمبورغي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Malagasy', 'name_ar' => 'مدغشقري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Malawian', 'name_ar' => 'مالاوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Malaysian', 'name_ar' => 'ماليزي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Maldivian', 'name_ar' => 'مالديفي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Malian', 'name_ar' => 'مالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Maltese', 'name_ar' => 'مالطي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Marshallese', 'name_ar' => 'جزر مارشالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Mauritian', 'name_ar' => 'موريشيوسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Micronesian', 'name_ar' => 'ميكرونيزي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Monegasque', 'name_ar' => 'موناكوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Mongolian', 'name_ar' => 'منغولي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Mozambican', 'name_ar' => 'موزمبيقي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Myanmarese', 'name_ar' => 'ميانماري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Namibian', 'name_ar' => 'ناميبي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Nauruan', 'name_ar' => 'ناوروي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Nepali', 'name_ar' => 'نيبالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Nicaraguan', 'name_ar' => 'نيكاراغوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Nigerien', 'name_ar' => 'نيجري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'North Korean', 'name_ar' => 'كوري شمالي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Palauan', 'name_ar' => 'بالاوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Papua New Guinean', 'name_ar' => 'بابوا غيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Filipino', 'name_ar' => 'فلبيني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Rwandan', 'name_ar' => 'رواندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Saint Kittitian', 'name_ar' => 'سانت كيتسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Saint Lucian', 'name_ar' => 'سانت لوسي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Vincentian', 'name_ar' => 'فينسنتي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Samoan', 'name_ar' => 'ساموي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Sammarinese', 'name_ar' => 'سان مارينوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Sao Tomean', 'name_ar' => 'ساو تومي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Seychellois', 'name_ar' => 'سيشلي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Sierra Leonean', 'name_ar' => 'سيراليوني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Singaporean', 'name_ar' => 'سنغافوري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Solomon Islander', 'name_ar' => 'جزر سليماني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'South Sudanese', 'name_ar' => 'جنوب سوداني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Sri Lankan', 'name_ar' => 'سريلانكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Surinamese', 'name_ar' => 'سورينامي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Taiwanese', 'name_ar' => 'تايواني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Tajik', 'name_ar' => 'طاجيكي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Tanzanian', 'name_ar' => 'تنزاني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Timorese', 'name_ar' => 'تيموري', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Togolese', 'name_ar' => 'توغولي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Tongan', 'name_ar' => 'تونغي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Trinidadian', 'name_ar' => 'ترينيدادي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Turkmen', 'name_ar' => 'تركماني', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Tuvaluan', 'name_ar' => 'توفالوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Ugandan', 'name_ar' => 'أوغندي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Vanuatuan', 'name_ar' => 'فانواتوي', 'category' => 'FOREIGN', 'sort_order' => 100],
            ['name_en' => 'Vatican', 'name_ar' => 'فاتيكاني', 'category' => 'FOREIGN', 'sort_order' => 100],
        ];

        foreach ($nationalities as $nat) {
            DB::table('nationalities')->insert(array_merge($nat, ['created_at' => now(), 'updated_at' => now()]));
        }
    }
}
