<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        $updates = [
            'سعود يوسف الجناعي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'لم تتم',
            ],
            'خالد محمد الحجه - محترف' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انتظار',
            ],
            'حسين علي المطوع' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'العربي',
            ],
            'فراس بن محمد بن خالد الخيبري' => [
                'contract_fees' => 600.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'تجديد',
            ],
            'فارس إبراهيم رمضان' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'سبونسر',
            ],
            'حسن علي حسين' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نادي الكرخ',
                'position' => 'مهاجم',
                'email' => 'hassan8ali2006@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '9647772448067',
            ],
            'محمد بن حسن بن عبدالله الحسن' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'لم تتم',
                'position' => 'CAM/CM/ST/LW',
                'previous_clubs' => '["لاعب حر"]',
                'email' => 'ooiikkhh55@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966546045497',
            ],
            'يوسف ابراهيم العتيبي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
            ],
            'فواز مزيد عبد الله جدعان الرشيدي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الشاميه',
            ],
            'أحمد فيصل أحمد الخضر' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الشاميه',
                'position' => 'جناح وصانع ألعاب وسترايكر',
                'email' => 'ahmadalkhudher10@outlook.com',
                'preferred_foot' => 'BOTH',
                'phone' => '96569600030',
            ],
            'جاسم محمد حسن' => [
                'contract_fees' => 150.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انتظار',
            ],
            'عذبي فهد نهار المطيري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انتظار',
            ],
            'متعب فهد نهار المطيري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سبورتي',
            ],
            'نايف مضحي شويمي العازمي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'تم النصر سنتين',
                'position' => 'حارس',
                'email' => 'Nayef.9837@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96596640805',
            ],
            'جمال محمود جمال حسن جمال' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الشاميه',
            ],
            'محمد أسامة محمد تقي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الشامية',
                'position' => 'قلب دفاع',
                'email' => 'bgtaqi.druid@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96565616846',
            ],
            'مشعل سعد عواد الحيص' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'استمرار الكويت',
                'position' => 'وسط',
                'email' => 'Mshlsaadgjg@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96594158421',
            ],
            'عبد الرحمن صلاح خلف العنزي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سبورتي',
            ],
            'عبد العزيز صلاح خلف العنزي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انهاء عقد استمرار السالميه',
                'position' => 'وسط',
                'email' => 'al3nzii393@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96551198684',
            ],
            'محمد محمود عبد الجيل محمد' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'بدون نادي',
                'position' => 'باك يسار وقلب جناح',
                'email' => 'm.alm7md4@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96562229693',
            ],
            'يوسف طارق عبد الحميد ماضي' => [
                'contract_fees' => 100.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سبورتي',
            ],
            'حسام علي محمد أبو ذهب' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سبورتي',
            ],
            'سالم محمد جاسم الهولي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'سبورتي',
            ],
            'فواز مبارك الشمري' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الشاميه',
                'position' => 'CB/CDM/RB',
                'email' => 'Fawazalhehe@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96599938976',
            ],
            'حسين عبد المحسن محمد الحسيني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'استمارار مع الكويت',
            ],
            'عبد العزيز عبدالرحمن منيف العتيبي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انتظار',
            ],
            'خالد حمود العصيمي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انتظار',
            ],
            'مبارك عبد الناصر السداني' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الشاميه',
                'position' => 'LB/RB/LW/RW',
                'email' => 'mbarak6262@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96550552358',
            ],
            'لیان عادل عبدالله القامس' => [
                'contract_fees' => 0.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انتظار',
            ],
            'سلمان صقر الظفيري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الساحل 300',
            ],
            'علي سلمان علاء الدين' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'صليبخات',
                'position' => 'مهاجم وجناح ايمن وايسر',
                'email' => 'Alaaedineali3@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96170977650',
            ],
            'طلال مزيد عبد الكريم العنزي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'وسط',
                'email' => 'Tenzi659@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96555660883',
            ],
            'ناصر خالد حاجي الفلكاوي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'برقان',
            ],
            'عبدالله خلف عبدالله الصولة' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'العربي استمرار',
                'position' => 'CB/RB/RWB',
                'email' => 'abdullahkhalafalsoulah5@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96566256236',
            ],
            'نوف فهد ماجد السبيعي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انهاء عقد',
            ],
            'عمر أحمد محمد الشايع' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'النصر',
            ],
            'مشاري أحمد ريس السوادي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انهاء عقد',
            ],
            'ناصر سالم مبارك سعيد' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'العربي',
                'position' => 'قلب دفاع',
                'email' => 'Nasseralsaeed7@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96590076454',
            ],
            'يوسف صلاح عبد الله الفجي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الجزيره',
            ],
            'عبد الرحمن فوزي الرياحي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انتظار',
            ],
            'ثامر صلاح عوض الهبيده' => [
                'contract_fees' => 100.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'فصخ عقد',
            ],
            'محمد ضاحي عطية الشمري' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'اليرموك برقان سبورتي',
            ],
            'إبراهيم علي حسين إسماعيل' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'تجارب',
            ],
            'عبد الله حمد عوض المطيري' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'بدون نادي',
                'position' => 'وسط',
                'email' => 'Theourmistake@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96598777826',
            ],
            'وليد خالد جاسم التورة' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'خيطان',
                'position' => 'وسط',
                'email' => 'Waltoura7@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96594946977',
            ],
            'راشد صلاح دابس الرشيدي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => '300 برقان',
                'position' => 'RM/LM/CAM/CM',
                'email' => 'Rasheddabes@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96597777066',
            ],
            'يوسف خالد عبدالرضا كرم' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'بدون نادي',
                'position' => 'LW/RW/ST',
                'email' => 'aldewanea2026@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '50241010',
            ],
            'محمد بن احمد الجرفي النخلي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نادي العلا',
                'position' => 'ظهير يمين وقلب دفاع',
                'email' => 'Mahmmad.j.28@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966565505393',
            ],
            'عقيل ناصر موسى الهزيم' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'اليرموك ٦٠٠',
            ],
            'عبدالله مطلق الجاسر' => [
                'contract_fees' => 150.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'برقان و النصر تجربه',
            ],
            'صالح عقيل كرامه المهري' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'لاعب حر',
                'position' => 'جناح يمين و يسار وباك يمين',
                'email' => 'salehaqeel2004@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96566460753',
            ],
            'عبدالله أحمد عبدالله شلال' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الحالة البحريني',
                'position' => 'قلب دفاع',
                'email' => 'abdullashallal5@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '97333901080',
            ],
            'ابراهيم عبد الكريم ابراهيم التميمي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'سبورتي',
            ],
            'خالد عبدالرزاق مرزوق العنزي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'بدون نادي',
                'position' => 'باك يمين وباك يسار',
                'preferred_foot' => 'BOTH',
                'phone' => '96597558321',
            ],
            'أحمد منصور أحمد البلوشي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'استمرار الشباب',
            ],
            'علي وليد علي  جمعة' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سبورتي تجربه والشاميه',
            ],
            'عبد الكريم جراغ' => [
                'contract_fees' => 150.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'السالمية تجربه',
            ],
            'احمد فهد سلطان سالم' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'خيطان تجربه',
            ],
            'عبد الله ناصر موسى بومجداد' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'السالمية',
                'position' => 'تحت مهاجم وجناح ايمن',
                'email' => 'alnasser.a2003@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96566533599',
            ],
            'محمد ابو بكر تركي محمد الامين' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الشاميه',
            ],
            'فواز على ربيح مفرح الرشيدي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الشاميه',
                'position' => 'RW/LW/RB',
                'email' => 'Fawazalrshedii7@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96566707477',
            ],
            'ياسر بن عزيز بن حمود الحسيني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'محور8/6',
                'email' => 'alharbi.iyaser1@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966563448341',
            ],
            'مناف بن أحمد بن حمدان الشمراني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الحزم السعودي',
                'position' => 'ظهير أيمن',
                'email' => 'manafalshmrani@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966560343262',
            ],
            'ريان بن سعود بن فاضل الربيعة الشمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الجندل',
                'position' => 'ظهير يمين ويسار',
                'email' => 'kkllo0112@icloud.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966560295961',
            ],
            'عبد العزيز بن محمد بن حسن غروي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
            ],
            'سلطان بن عبد الله بن عيد السريحي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'انهاء عقد',
            ],
            'عزام بن عبد الله بن محمد العبيد' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الهلالية',
                'position' => 'ظهير يسار ومدافع',
                'email' => 'v2azam328@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966556511328',
            ],
            'نواف فيصل خميس' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الخالدية',
                'position' => 'CM',
                'email' => 'fnawaf43@yahoo.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966503903293',
            ],
            'مقتدى بن محمد بن علي آل مزعل' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الهداية',
                'position' => 'جناح ايسر وصانع ألعاب',
                'email' => 'Muqtada1432@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966560558696',
            ],
            'فيصل بن عيسى بن سالم العلوي الحربي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'محور ارتكاز وظهير ايمن',
                'email' => 'muntiii566@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966532712708',
            ],
            'أحمد بن عبدالله البلوشي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
            ],
            'فهد بن محمد بن عيسى الحفه' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الساحل',
                'position' => 'ظهير يمين',
                'email' => 'fahadmohamd2020@icloud.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966549493253',
            ],
            'محمد أمين منصط' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'تم فسخ العقد',
                'position' => 'جناح ايسر/خط وسط هجوم',
                'email' => 'info.medamine7@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966533707316',
            ],
            'عمار بن زهير با سيف' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'جناح يمين ويسار',
                'email' => 'ammarbasaif@yahoo.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966557564607',
            ],
            'محمد بن شوقي محمد آل نمر' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'جناح ايمن وايسر وصانع ألعاب',
                'email' => 'mohammed11alnemer@hotmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966547281344',
            ],
            'عبد الرحمن لافي خزعل الخالدي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'position' => 'RB/LB/RW/LW/CM',
                'email' => 'Al5aldy2003@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96550108105',
            ],
            'بندر بن علي الاحمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نجران',
                'position' => 'محور وظهير ايمن',
                'email' => 'bndralahmry02@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966538973138',
            ],
            'علي رضا مهدي منظمي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'forward',
                'email' => 'Alirezamonazami81@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '989015295608',
            ],
            'عبد الرحمن إيهاب فكري جمعة العجمي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'لاعب حر',
                'position' => 'باك ليفت/سرد باك',
                'email' => 'abdogsvagsg@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966549646364',
            ],
            'يوسف بن مسفر بن محمد السني الزهراني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'سدير إنهاء العقد',
                'position' => 'حارس',
                'email' => 'mwnbysy@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966544919296',
            ],
            'عبد العزيز دهام نداء الشمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الكويت',
                'position' => 'ST وجناح يمين',
                'email' => '‏Azez.25@icloud.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96599285638',
            ],
            'عمر حمدان حامد الهجلة المطيري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'النجمة السعودي',
                'position' => 'صانع ألعاب ومهاجم',
                'email' => 'ouwiha111@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966558230235',
            ],
            'باسل بن بسام بن حسن ادول' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'ظهير ايمن وايسر',
                'email' => 'badwl467@gmali.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966565773188',
            ],
            'ياسر بن محمد بن صالح السعيد' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'محور',
                'email' => 'yasser_1409686@icloud.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966562690544',
            ],
            'محمد بدر ناصر القحطاني' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'فيصل مفرح خضر العنزي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'عمر أكرم علي حماد' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'نادي الكويت',
                'position' => 'CAM/RW/LW',
                'email' => 'omarakram1010gg@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96550752735',
            ],
            'محمد علي محمد آل سنيان البسيسي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'يرغب في ان يكمل دراستة',
            ],
            'خالد فيصل عوض آل العرام القحطاني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'الروضة السعودي',
                'position' => 'ظهير يسار',
                'email' => 'khaledalqahtani684@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966547685424',
            ],
            'لؤي عطية حسين النخلي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'لاعب حر',
                'position' => 'ظهير ايمن وقلب دفاع',
                'email' => 'lwylwlw16@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966590316600',
            ],
            'آدم أحمد عبد الله خاطر' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'محمد شهاب أحمد كنكوني' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'عزام بن خالد بن عبدالله الذياب' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'محور 8/6',
                'email' => 'xv66vx@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966554581780',
            ],
            'ابراهيم عبد العزيز المحيميد' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نادي النجمة',
                'position' => 'حارس',
                'email' => 'g30874653@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966535131390',
            ],
            'المثنى بن أحمد إبراهيم الدخيل' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'محور',
                'email' => 'Mothani.11.2019@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966540454672',
            ],
            'محمد حسين درويش عباس' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'سعد بن محمد بن عبدالله البيشي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'لاعب حر',
                'position' => 'ظهير يمين ويسار',
                'email' => 'sd987739@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966509569058',
            ],
            'ممدوح بن موسى بن محمد حزام' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'جدة',
                'position' => 'ظهير ايمن',
                'email' => 'm0553447487@icloud.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966566629487',
            ],
            'زياد بن جمال بن راشد العجلاني' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'لاعب وسط وظهير ايمن وايسر',
                'email' => 'zyaood55@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966502568182',
            ],
            'عبدالله بن عبدالعزيز بن حمد العمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي',
                'position' => 'مهاجم',
                'email' => 'abdullahalomari47@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '966500035483',
            ],
            'علي كمال علي الخرس' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'انتهاء العقد',
                'position' => 'راس حربه وتحت مهاجم',
                'email' => 'aalkhars150@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96599864261',
            ],
            'حمد طارق محمد عبد السلام' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'عبدالله خالد سيف الشطي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'العربي',
                'position' => 'تحت مهاجم',
                'email' => 'aalshatti964@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96594451281',
            ],
            'محمد هيثم حيدر' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'بدون نادي إنهاء عقد',
                'position' => 'محور وصانع ألعاب',
                'email' => 'mohammedmho321@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966531058565',
            ],
            'محمد أسامة كرم سيد خليل' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'بدون نادي',
                'position' => 'جناح يمين و وسط مهاجم',
                'email' => 'mo7mdking99@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96566514369',
            ],
            'عبد المحسن فهد محمد العجمي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الجزيرة',
                'position' => 'RB/LB',
                'email' => 'kuwait16653@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96594176000',
            ],
            'فهد محمد حسين الشريف' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'نادي كاظمة',
                'position' => 'جناح ايمن وجناح ايسر',
                'email' => 'falshreef03@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96597740292',
            ],
            'مروان سليم' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
            ],
            'عبد الله حسين العنزي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'position' => 'CM/CDM',
                'email' => 'abdallahkwlllll@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96598780198',
            ],
            'عبد العزيز مصطفي الديب' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'position' => 'خط وسط',
                'email' => 'zezo.sincara@gmail.com',
                'preferred_foot' => 'BOTH',
                'phone' => '96550808502',
            ],
            'عبد العزيز مصطفى عبد العزيز الديب' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'نواف غالب سيف يافعي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نادي عالي تحت 23]',
                'position' => 'LB , LW , RW',
                'email' => 'rawaaf.alyafie.123456789@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '966530848277',
            ],
            'سليمان داوود فيروز فرحان' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'نادي التضامن',
                'position' => 'قلب دفاع وباك يمين',
                'email' => 'Sulaimandawood112244@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '96565758017',
            ],
            'عمر صلاح الشرهان' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'نادي الفيحاء',
                'position' => 'قلب دفاع',
                'email' => 'alshrhanmr651@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966508745811',
            ],
            'بدر جلال جمال' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'position' => 'CDM/CB/CM/LB/',
                'email' => 'Bader.Jamal42@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96594746144',
            ],
            'فهد سعد الاسمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'المالكية البحريني',
                'position' => 'مهاجم وجناح ايمين وايسر',
                'email' => 'fahadalasmari27@gmail.com',
                'preferred_foot' => 'RIGHT',
                'phone' => '966506027666',
            ],
            'تركي منيف الشمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'position' => 'ظهير ايسر',
                'email' => 'botrikah@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96599940804',
            ],
            'عبد الله حسن بهمن' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'العربي',
                'position' => 'حارس مرمي',
                'email' => 'Abahman2830@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96567772225',
            ],
            'بدر سالم راشد الشمري' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
                'deal_status' => 'العربي',
                'position' => 'تحت مهاجم / جناح ايمن وايسر',
                'email' => 'badran22006@gmail.com',
                'preferred_foot' => 'LEFT',
                'phone' => '96566830535',
            ],
            'هاني سالم محمد الصقر' => [
                'deal_status' => 'انتهى',
            ],
            'محمد صهيب أمين' => [
                'contract_fees' => 250.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'اليرموك',
            ],
            'عبد الله عايض العتيبي' => [
                'contract_fees' => 250.0,
                'contract_fees_type' => 'FIXED',
            ],
            'سليم بن هادي العياري' => [
            ],
            'عبد الرحمن عبد العزيز البلوشي' => [
                'contract_fees' => 300.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'خيطان',
            ],
            'طارق بن نور الدين' => [
            ],
            'علي العماري محمد' => [
            ],
            'حمزة فاضل محمد الصراف' => [
            ],
            'يوسف عبد الكريم تقي علي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
            ],
            'رافع عبد الرزاق هرابي' => [
                'contract_fees' => 200.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'العربي',
            ],
            'عبد الله محمد حمد محمد محمود' => [
                'contract_fees' => 350.0,
                'contract_fees_type' => 'FIXED',
                'deal_status' => 'الجهراء',
            ],
            'الطربلسي مدرب حراس' => [
                'deal_status' => 'الجهراء',
            ],
            'علي خليفة عبد السيد العلي' => [
                'contract_fees' => 10.0,
                'contract_fees_type' => 'PERCENTAGE',
            ],
        ];

        foreach ($updates as $name => $data) {
            DB::table('players')
                ->where('name_ar', $name)
                ->orWhere('name', $name)
                ->update(array_merge($data, ['updated_at' => now()]));
        }
    }

    public function down(): void
    {
    }
};
